name: PHPUnit

on:
  push:
    branches: [ develop-v2 ]
  pull_request:
    branches: [ develop-v2 ]

jobs:
  php-7.2:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout repository
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        TELEGRAM_BOT_NAME: ${{ secrets.TELEGRAM_BOT_NAME }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_LOG_CHAT_ID: ${{ secrets.TELEGRAM_LOG_CHAT_ID }}
      run: vendor/bin/phpunit --testdox

  php-7.3:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout repository
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        TELEGRAM_BOT_NAME: ${{ secrets.TELEGRAM_BOT_NAME }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_LOG_CHAT_ID: ${{ secrets.TELEGRAM_LOG_CHAT_ID }}
      run: vendor/bin/phpunit --testdox


  php-7.4:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout repository
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        TELEGRAM_BOT_NAME: ${{ secrets.TELEGRAM_BOT_NAME }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_LOG_CHAT_ID: ${{ secrets.TELEGRAM_LOG_CHAT_ID }}
      run: vendor/bin/phpunit --testdox

  php-8.0:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout repository
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: vendor/bin/phpunit --testdox
